### ISSUE TITLE
Repository: What direction this repository should take?

### ISSUE THREAD

**Issue by JeffLabonte** [roaldi/System76-Utilities#10]
Hey guys! 

I have noticed that @ahoneybun added a user interface to work with the backlight on an S76 laptop. This is awesome, but it makes me wonder, @roaldi, should this repository become "Keyboard Color Switcher"? or should I make another repository and use what I have pushed here? 

The work I have put in the `battery-backlight` can easily be integrated into a GTK Application. I already have the configurations and everything. I mean, it has a lot of work put into it, and the effort to make a UI out of it would be fun and relatively easy! 

You are the owner of the repository. It is your call. It also depends on how comfortable you are in this situation. 😄

**Comment by ahoneybun** [comment]
I would love help with the tool! Please do let me know!

**Comment by JeffLabonte** [comment]
@ahoneybun I am down to help out 😄

**Comment by ahoneybun** [comment]
:tada: https://github.com/ahoneybun/keyboard-color-chooser

**Comment by yochananmarqos** [comment]
I would say it should be (and has already started to be) a central hub for scripts and projects. Collect scripts and link to other repos.

@JeffLabonte There probably shouldn't be a `Makefile` in the main folder since more things are being added now.

**Comment by JeffLabonte** [comment]
@yochananmarqos More than I think about it I should probably change my PR to remove the Makefile altogether

**Comment by habitualdev** [comment]
I would like this to be first and foremost  a central point for scripts and other repos to be shared from.  I feel part of what I want this to be is a jump point for creativity, where someone sees a script they can use, a config file that's useful, etc. 

That being said, I do think it would be worth pursuing a single GTK application that is a meaningful combination of the most popular/most useful items. Something like that would be mainly advertised for those less code-savvy people that still want to do cool things.

I'd like to hear everyone's thoughts on that direction - continue collecting scripts and utilities, but coalesce core features into a single distributed application.

**Comment by ahoneybun** [comment]
Are we talking about just the keyboard features then? If so then I agree, the rest of the stuff may be tough to link together.

**Comment by habitualdev** [comment]
I think the keyboard features will probably be a big part. Not only is it a very visible part of the laptop, shiny, blinky lights interest everyone. But also adding in stuff to make all the nice stuff the System76 firmware adds accessible to everyone should be the goal.

**Comment by JeffLabonte** [comment]
I feel like `backlight-battery` should have its own repository since it has become quite quickly a piece of software of its own. We could add submodules to this repository linking all the projects that we want.

The user interface being worked out by @ahoneybun could be a submodule in this repository instead of having a whole copy of the project. We could make this repo a hub of scripts as you describe it.

I could distribute `backlight-battery` on Pypi and adapt it to work a few more things, such as KCS. As you might have noticed, I am working as a software engineer, so I am kind of code-savvy :stuck_out_tongue:

**Comment by habitualdev** [comment]
Yeah, I like that, I think. This repo just being a crossroads, with my own sprinkling of bash-ery, leading to the more serious stuff you guys have done.

**Comment by habitualdev** [comment]
Like I mentioned to @ahoneybun, I didn't expect this much response, or rather, this serious a response. I thought it was going to be a collection of shell scripts that people could grab and use as they wanted. Definitely don't regret this direction, however.

**Comment by JeffLabonte** [comment]
Thank you everyone for taking the time to answer my question! I really appreciate it :smile:
