### ISSUE TITLE
keyboard-color-switcher dconf-WARNING

### ISSUE THREAD

**Issue by yochananmarqos** [roaldi/System76-Utilities#9]
@ahoneybun The application works fine on my Serval WS (serw12), thanks for sharing. 

However, it spits out the following every time the color is changed. Any idea why? I'm using Manjaro GNOME on X11.

```
(keyboard-color-switcher:329961): dconf-WARNING **: 13:40:48.098: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=7a2551911753462a8e997be0eab9c8f6 --binary-syntax --close-stderr”: Child process exited with code 1
left
FFFF00
````

**Comment by ahoneybun** [comment]
There are print lines for debugging. You can either remove the lines or ignore them.

**Comment by yochananmarqos** [comment]
Ah, okay. Just curious.
